"""All 47 Kenya counties with GPS coordinates and main crops."""

KENYA_COUNTIES = [
    {"name":"Baringo","lat":0.4669,"lon":35.9668,"region":"Rift Valley"},
    {"name":"Bomet","lat":-0.7820,"lon":35.3420,"region":"Rift Valley"},
    {"name":"Bungoma","lat":0.5635,"lon":34.5606,"region":"Western"},
    {"name":"Busia","lat":0.4607,"lon":34.1116,"region":"Western"},
    {"name":"Elgeyo-Marakwet","lat":1.0504,"lon":35.4902,"region":"Rift Valley"},
    {"name":"Embu","lat":-0.5300,"lon":37.4500,"region":"Eastern"},
    {"name":"Garissa","lat":-0.4532,"lon":39.6461,"region":"North Eastern"},
    {"name":"Homa Bay","lat":-0.5273,"lon":34.4571,"region":"Nyanza"},
    {"name":"Isiolo","lat":0.3540,"lon":37.5820,"region":"Eastern"},
    {"name":"Kajiado","lat":-2.0987,"lon":36.7819,"region":"Rift Valley"},
    {"name":"Kakamega","lat":0.2827,"lon":34.7519,"region":"Western"},
    {"name":"Kericho","lat":-0.3690,"lon":35.2863,"region":"Rift Valley"},
    {"name":"Kiambu","lat":-1.0310,"lon":36.8309,"region":"Central"},
    {"name":"Kilifi","lat":-3.5107,"lon":39.9093,"region":"Coast"},
    {"name":"Kirinyaga","lat":-0.6594,"lon":37.3824,"region":"Central"},
    {"name":"Kisii","lat":-0.6817,"lon":34.7669,"region":"Nyanza"},
    {"name":"Kisumu","lat":-0.1022,"lon":34.7617,"region":"Nyanza"},
    {"name":"Kitui","lat":-1.3667,"lon":38.0167,"region":"Eastern"},
    {"name":"Kwale","lat":-4.1830,"lon":39.4606,"region":"Coast"},
    {"name":"Laikipia","lat":0.3606,"lon":36.7819,"region":"Rift Valley"},
    {"name":"Lamu","lat":-2.2694,"lon":40.9023,"region":"Coast"},
    {"name":"Machakos","lat":-1.5177,"lon":37.2634,"region":"Eastern"},
    {"name":"Makueni","lat":-2.2558,"lon":37.8938,"region":"Eastern"},
    {"name":"Mandera","lat":3.9366,"lon":41.8670,"region":"North Eastern"},
    {"name":"Marsabit","lat":2.3284,"lon":37.9899,"region":"Eastern"},
    {"name":"Meru","lat":0.0469,"lon":37.6490,"region":"Eastern"},
    {"name":"Migori","lat":-1.0634,"lon":34.4731,"region":"Nyanza"},
    {"name":"Mombasa","lat":-4.0435,"lon":39.6682,"region":"Coast"},
    {"name":"Murang'a","lat":-0.7833,"lon":37.0333,"region":"Central"},
    {"name":"Nairobi","lat":-1.2921,"lon":36.8219,"region":"Nairobi"},
    {"name":"Nakuru","lat":-0.3031,"lon":36.0800,"region":"Rift Valley"},
    {"name":"Nandi","lat":0.1833,"lon":35.1167,"region":"Rift Valley"},
    {"name":"Narok","lat":-1.0820,"lon":35.8700,"region":"Rift Valley"},
    {"name":"Nyamira","lat":-0.5667,"lon":34.9333,"region":"Nyanza"},
    {"name":"Nyandarua","lat":-0.1833,"lon":36.5167,"region":"Central"},
    {"name":"Nyeri","lat":-0.4167,"lon":36.9500,"region":"Central"},
    {"name":"Samburu","lat":1.2167,"lon":36.9500,"region":"Rift Valley"},
    {"name":"Siaya","lat":0.0607,"lon":34.2880,"region":"Nyanza"},
    {"name":"Taita-Taveta","lat":-3.3167,"lon":38.3500,"region":"Coast"},
    {"name":"Tana River","lat":-1.2833,"lon":39.8333,"region":"Coast"},
    {"name":"Tharaka-Nithi","lat":-0.3000,"lon":37.9167,"region":"Eastern"},
    {"name":"Trans Nzoia","lat":1.0500,"lon":34.9500,"region":"Rift Valley"},
    {"name":"Turkana","lat":3.1167,"lon":35.5667,"region":"Rift Valley"},
    {"name":"Uasin Gishu","lat":0.5200,"lon":35.2699,"region":"Rift Valley"},
    {"name":"Vihiga","lat":0.0833,"lon":34.7167,"region":"Western"},
    {"name":"Wajir","lat":1.7471,"lon":40.0573,"region":"North Eastern"},
    {"name":"West Pokot","lat":1.7500,"lon":35.1167,"region":"Rift Valley"},
]

COUNTY_MAP = {c["name"]: c for c in KENYA_COUNTIES}

COUNTY_CROPS = {
    "Baringo":["Maize","Sorghum","Millet","Milk"],
    "Bomet":["Tea","Maize","Milk"],
    "Bungoma":["Sugarcane","Maize","Beans"],
    "Busia":["Maize","Sugarcane","Fish"],
    "Elgeyo-Marakwet":["Maize","Wheat","Milk"],
    "Embu":["Coffee","Tea","Maize","Beans"],
    "Garissa":["Livestock","Maize"],
    "Homa Bay":["Fish","Maize","Sorghum"],
    "Isiolo":["Livestock","Maize"],
    "Kajiado":["Milk","Maize","Vegetables"],
    "Kakamega":["Sugarcane","Maize","Bananas"],
    "Kericho":["Tea","Maize","Milk"],
    "Kiambu":["Tea","Coffee","Avocado","Potatoes","Tomatoes"],
    "Kilifi":["Coconut","Cashew","Cassava","Maize"],
    "Kirinyaga":["Rice","Coffee","Maize"],
    "Kisii":["Tea","Maize","Bananas"],
    "Kisumu":["Maize","Sorghum","Fish","Rice"],
    "Kitui":["Maize","Sorghum","Cotton","Mangoes"],
    "Kwale":["Sugarcane","Cassava","Coconut"],
    "Laikipia":["Maize","Wheat","Milk","Livestock"],
    "Lamu":["Fish","Coconut","Cashew"],
    "Machakos":["Maize","Beans","Mangoes","Tomatoes"],
    "Makueni":["Maize","Beans","Mangoes","Avocado"],
    "Mandera":["Livestock"],
    "Marsabit":["Livestock","Maize"],
    "Meru":["Tea","Coffee","Miraa","Potatoes","Maize"],
    "Migori":["Maize","Sugarcane","Fish"],
    "Mombasa":["Fish","Coconut","Cassava","Bananas"],
    "Murang'a":["Coffee","Tea","Avocado","Bananas"],
    "Nairobi":["Tomatoes","Vegetables","Onions"],
    "Nakuru":["Maize","Wheat","Potatoes","Milk"],
    "Nandi":["Tea","Maize","Milk"],
    "Narok":["Maize","Wheat","Milk","Barley"],
    "Nyamira":["Tea","Maize","Bananas"],
    "Nyandarua":["Potatoes","Milk","Wheat","Maize"],
    "Nyeri":["Coffee","Tea","Maize","Potatoes"],
    "Samburu":["Livestock"],
    "Siaya":["Maize","Sorghum","Fish"],
    "Taita-Taveta":["Maize","Beans","Tomatoes"],
    "Tana River":["Maize","Rice","Livestock"],
    "Tharaka-Nithi":["Maize","Beans","Miraa"],
    "Trans Nzoia":["Maize","Wheat","Milk"],
    "Turkana":["Livestock","Sorghum"],
    "Uasin Gishu":["Maize","Wheat","Milk","Sunflower"],
    "Vihiga":["Maize","Tea","Vegetables"],
    "Wajir":["Livestock"],
    "West Pokot":["Maize","Sorghum","Livestock"],
}

REGIONS = {}
for _c in KENYA_COUNTIES:
    REGIONS.setdefault(_c["region"], []).append(_c["name"])

REGION_ORDER = ["Nairobi","Central","Eastern","Coast",
                "Nyanza","Western","Rift Valley","North Eastern"]

def get_county(name): return COUNTY_MAP.get(name)
def get_county_names(): return [c["name"] for c in KENYA_COUNTIES]
def get_county_crops(name): return COUNTY_CROPS.get(name, ["Maize","Beans"])
